INSERT INTO ADMIN.DIM_DATE (DATE_ID, DAY, MONTH, MONTH_NAME, QUARTER, YEAR, WEEKDAY) 
VALUES (DATE '2023-01-01', 1, 1, 'January', 1, 2023, 'Sunday');

INSERT INTO ADMIN.DIM_DATE (DATE_ID, DAY, MONTH, MONTH_NAME, QUARTER, YEAR, WEEKDAY) 
VALUES (DATE '2023-01-02', 2, 1, 'January', 1, 2023, 'Monday');

INSERT INTO ADMIN.DIM_DATE (DATE_ID, DAY, MONTH, MONTH_NAME, QUARTER, YEAR, WEEKDAY) 
VALUES (DATE '2023-08-01', 1, 8, 'August', 3, 2023, 'Tuesday');


INSERT INTO ADMIN.DIM_PROD (PROD_NAME, CATEGORY, PRICE, STOCK_QUANTITY, PROD_DESC, VENDOR_NAME)
VALUES ('Gaming Laptop', 'Electronics', 1500.00, 50, 'High performance', 'TechWare');

INSERT INTO ADMIN.DIM_PROD (PROD_NAME, CATEGORY, PRICE, STOCK_QUANTITY, PROD_DESC, VENDOR_NAME)
VALUES ('Bluetooth Speaker', 'Audio', 120.00, 100, 'Portable', 'SoundBuzz');

INSERT INTO ADMIN.DIM_CUST (CUST_NAME, AGE, GENDER, LOCATION, PHONE, EMAIL)
VALUES ('Alice Johnson', 30, 'Female', 'New York', '555-1234', 'alice@example.com');

INSERT INTO ADMIN.DIM_CUST (CUST_NAME, AGE, GENDER, LOCATION, PHONE, EMAIL)
VALUES ('Bob Smith', 45, 'Male', 'Los Angeles', '555-5678', 'bob@example.com');

INSERT INTO ADMIN.DIM_EMP (EMP_NAME, EMP_POSITION, HIRE_DATE)
VALUES ('Emily Clark', 'Sales Rep', DATE '2021-06-15');

INSERT INTO ADMIN.DIM_EMP (EMP_NAME, EMP_POSITION, HIRE_DATE)
VALUES ('John Doe', 'Manager', DATE '2020-01-10');

INSERT INTO ADMIN.DIM_STORE (NAME, LOCATION, TYPE, OPENING_DATE)
VALUES ('Downtown Hub', 'New York', 'Retail', DATE '2019-03-01');

INSERT INTO ADMIN.DIM_STORE (NAME, LOCATION, TYPE, OPENING_DATE)
VALUES ('Westside Outlet', 'Los Angeles', 'Retail', DATE '2020-07-15');

INSERT INTO ADMIN.DIM_PROMOTION (NAME, START_DATE, END_DATE, DISCOUNT_PERCENT, DISCOUNT_IN_PRICE)
VALUES ('Summer Sale', DATE '2023-07-01', DATE '2023-08-31', 15.00, 50.00);

INSERT INTO ADMIN.DIM_PROMOTION (NAME, START_DATE, END_DATE, DISCOUNT_PERCENT, DISCOUNT_IN_PRICE)
VALUES ('Holiday Deal', DATE '2023-12-01', DATE '2023-12-31', 20.00, 100.00);

INSERT INTO ADMIN.FACT_SALES_TRANS (DATE_ID, PROD_ID, CUST_ID, STORE_ID, EMP_ID, PROMO_ID, QUANTITY, TOTAL_AMT)
VALUES (TO_DATE('2023-08-01', 'YYYY-MM-DD'), 1, 1, 1, 1, 1, 1, 1450.00);

INSERT INTO ADMIN.FACT_SALES_TRANS (DATE_ID, PROD_ID, CUST_ID, STORE_ID, EMP_ID, PROMO_ID, QUANTITY, TOTAL_AMT)
VALUES (TO_DATE('2023-08-01', 'YYYY-MM-DD'), 2, 2, 2, 2, 2, 2, 190.00);

INSERT INTO ADMIN.FACT_INVENTORY (PROD_ID, STORE_ID, DATE_ID, ON_HAND_QTY, RESERVED_QTY, DAMAGED_QTY, REORDER_QTY)
VALUES (1, 1, TO_DATE('2023-08-01', 'YYYY-MM-DD'), 30, 5, 1, 10);

INSERT INTO ADMIN.FACT_INVENTORY (PROD_ID, STORE_ID, DATE_ID, ON_HAND_QTY, RESERVED_QTY, DAMAGED_QTY, REORDER_QTY)
VALUES (2, 2, TO_DATE('2023-08-01', 'YYYY-MM-DD'), 90, 3, 0, 15);

SELECT
  S.TRANS_ID,
  D.DATE_ID,
  C.CUST_NAME,
  P.PROD_NAME,
  S.QUANTITY,
  S.TOTAL_AMT
FROM
  ADMIN.FACT_SALES_TRANS S
JOIN ADMIN.DIM_DATE D ON S.DATE_ID = D.DATE_ID
JOIN ADMIN.DIM_CUST C ON S.CUST_ID = C.CUST_ID
JOIN ADMIN.DIM_PROD P ON S.PROD_ID = P.PROD_ID;